config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :films do
    resources :comments
  root 'films#index'
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :film
end

app/models/film.rb
class Film < ActiveRecord::Base
 has_many :comments, dependent: :destroy
 validates :title, presence: true,
                    length: { minimum: 3 }


def self.search(query)
  where("title like ?", "%#{query}%") 
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", 
 only: :destroy

  def create
    @film = Film.find(params[:film_id])
    @comment = @film.comments.create(comment_params)
    redirect_to film_path(@film)
  end
 
  def destroy
    @film = Film.find(params[:film_id])
    @comment = @film.comments.find(params[:id])
    @comment.destroy
    redirect_to film_path(@film)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

def index
  if params[:search]
    @films = Film.search(params[:search]).order("created_at DESC")
  else
    @films = Film.all.order('created_at DESC')
  end
end


  def search
    @films = Film.find(params[:id])
  end



  def show
    @film = Film.find(params[:id])
  end

  def new
    @film = Film.new
  end

  def edit
    @film = Film.find(params[:id])
  end

  def create
    @film = Film.new(film_params)
 
    if @film.save
      redirect_to @film
    else
      render 'new'
    end
  end
  def update
    @film = Film.find(params[:id])
 
    if @film.update(film_params)
      redirect_to @film
    else
      render 'edit'
    end
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
   
    redirect_to films_path
  end
 
   private
     def film_params
       params.require(:film).permit(:title, :text)
     end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.film, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@film, @film.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/films/_form.html.erb
<%= form_for @film do |f| %>
 
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@film.errors.count, "error") %> prohibited
        this film from being saved:
      </h2>
      <ul>
        <% @film.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>
 
 
<%= render 'form' %>
 
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Listing films</h1>
 


<div class = "container">
<table class="table table-default">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @films.each do |film| %>
    <tr>
      <td><%= film.title %></td>
      <td><%= film.text %></td>
      <td><kbd><%= link_to 'Show ', film_path(film) %></kbd></td>
      <td><kbd><%= link_to 'Edit ', edit_film_path(film) %></kbd></td>
     <td><kbd><%= link_to 'Destroy', film_path(film),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></kbd></td
    </tr>
  <% end %>

</table>
</div>
<kbd><%= link_to 'New film', new_film_path %></kbd>
<%= form_tag(films_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search film" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/films/new.html.erb
<h1>New Film</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', films_path %>

app/views/films/search.html.erb
<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @film.text %>
</p>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @film.text %>
</p>


<h2>Comments</h2>
<% @film.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>FilmCrud</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
<%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<center>
<%= yield %>
</center>
</body>
</html>

app/views/welcome/index.html.erb
<div class = "navbar navbar-inverse">Hello, this is my app!</div>
<div class = "jumbotron">
<%= link_to 'MY FIRST CRUD WITH RUBY ON RAILS ', controller: 'films' %>
</div>